from pygame import USEREVENT

START = USEREVENT + 114

CREATE_NOTE = START + 1
DISPOSE_NOTE = START + 2
GAME_OVER = START + 3

HIDE_TAP_EFFECT = START + 4
RESERVED1 = START + 5
RESERVED2 = START + 6
RESERVED3 = START + 7
