from pygame import USEREVENT

START = USEREVENT + 114

CREATE_NOTE = START + 1
DISPOSE_NOTE = START + 2
GAME_OVER = START + 3

HIDE_TAP_EFFECT = START + 4
RESERVED1 = START + 5
RESERVED2 = START + 6
RESERVED3 = START + 7

HOLD_EARLY_RELEASE = START + 8

EXIT_CHART_INFO = START + 9
DECISION = START + 10

PLAY_MUSIC = START + 11